name: build adocs

on:
  push:
    branches:
    - main
    
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: Asciidoctoring the docs to pretty HTML! 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor -a stylesheet=style.css --backend=html5 -o index.html docs/index.adoc"
